### ISSUE TITLE
`{@link}` tags generate broken links

### ISSUE THREAD

**Issue by CobyPear** [HiDeoo/starlight-typedoc#32]
### Describe the bug

Hi. I'm pretty new to Astro so this may be a configuration issue but I wanted to open this just in case.

The Drupal API Client project just published docs built with Starlight and the TypeDoc plugin (thanks for this btw!). We noticed a few links are 404ing, specifically it seems like ones generated by typedoc `{@link}` tags. These particular ones are after a `@see` tag, but I see this behavior for other links too.

See https://project.pages.drupalcode.org/api_client/api/drupal-api-client/api-client/classes/apiclient/

### To Reproduce

1. Go to https://project.pages.drupalcode.org/api_client/api/drupal-api-client/api-client/classes/apiclient/
2. Click on either of the two links under `See`, "ApiClientOptions" or "BaseUrl".

**Expected**: the link takes you to the correct page
**Actual**: 404

### Expected behavior

Other links on that page seem to work fine. Here is an example of what the links look like in the plain markdown:

```md
[ApiClientOptions](../type-aliases/ApiClientOptions.md) and [BaseUrl](../type-aliases/BaseUrl.md)
```

The other links do not have the file extension and the last part of the path is all lowercase. It also seems the links don't go up enough levels. `../../type-aliases/apiclientoptions/` works in this case.

### How often does this bug happen?

Every time

### System Info

Reproducible locally on m2 macbook. The site linked above is built in GitLab CI.

### Additional Context

Here is our config:
```ts
        starlightTypeDoc({
          entryPoints: ["../packages/*"],
          output: "api",
          tsconfig: "../tsconfig.json",
          typeDoc: {
            entryPointStrategy: "packages",
            plugin: ["typedoc-plugin-mdn-links"],
            useCodeBlocks: true,
            navigationLinks: {
              "Project Page": "https://www.drupal.org/project/api_client",
            },
          },
        }),
```

Link to the repo if you are interested: https://git.drupalcode.org/project/api_client

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands:

This should now be fixed in [`v0.10.0`](https://github.com/HiDeoo/starlight-typedoc/releases/tag/v0.10.0) that has just been released.

**Comment by backlineint** [comment]
Thanks for the quick reply @HiDeoo ! I tested things with the latest release, and it doesn't appear to solve the issue @CobyPear reported. For example, the first link in our doc now points to: 

http://localhost:4321/api_client/api/drupal-api-client/api-client/drupal-api-client/api-client/type-aliases/apiclientoptions

That seems to include redundant path arguments `drupal-api-client/api-client` If I strip that, a link like:

http://localhost:4321/api_client/api/drupal-api-client/api-client/type-aliases/apiclientoptions

will work.

I've also noticed that links generated by the theme rather than by {@link} in content still seem to include the .md extension. For example, a link for the return signature of one of our classes ends up as:

http://localhost:4321/api_client/api/drupal-api-client/api-client/classes/apiclient/ApiClient.md

I did notice that if I change configuration to a single entry point {@links} seem to work on this latest release (links generated by the theme do not.) When using multiple entry points, or the packages entryPointStrategy (we're using packages) {@links} are broken as described above.

Let us know if we can provide any more info.

**Comment by HiDeoo** [comment]
Thanks for letting me know.

> Let us know if we can provide any more info.

I would say small example(s) with the mininal amount of code to reproduce the issue would be helpful, e.g. something like this kind of [fixtures](https://github.com/HiDeoo/starlight-typedoc/blob/main/fixtures/basics/src/Foo.ts) in the repo and the associated configuration file(s) to reproduce the issue.

>  links generated by the theme rather than by {@link} in content 

> links generated by the theme do not

Not quite sure what you mean by this. I guess an example would help too to understand the actual result and the expected one.

**Comment by backlineint** [comment]
@HiDeoo the {@link} case can be duplicated in one of the examples in this repo without any modification.

In examples directory:

- Run `pnpm dev:packages-entrypoints`
- View http://localhost:4321/packages-entrypoints/api-packages-entrypoints/foo/functions/dofoofaster/
- The link in 'This is a faster alternative to doFoo' will be broken.

Still working on a clearer example for the second case.
